//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuaför2
{
    using System;
    using System.Collections.Generic;
    
    public partial class değerlendirme
    {
        public int ID { get; set; }
        public Nullable<int> Puan { get; set; }
        public string Yorum { get; set; }
        public Nullable<int> Kuaför { get; set; }
        public Nullable<int> Müşteri { get; set; }
    
        public virtual Kuaför Kuaför1 { get; set; }
        public virtual müşteri müşteri1 { get; set; }
    }
}
