//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuaför2
{
    using System;
    using System.Collections.Generic;
    
    public partial class işlem_ücret
    {
        public int ID { get; set; }
        public Nullable<int> ücret { get; set; }
        public Nullable<int> kuaför { get; set; }
        public Nullable<int> işlem { get; set; }
    
        public virtual işlemler işlemler { get; set; }
        public virtual Kuaför Kuaför1 { get; set; }
    }
}
