//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuaför2
{
    using System;
    using System.Collections.Generic;
    
    public partial class işlemler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public işlemler()
        {
            this.işlem_ücret = new HashSet<işlem_ücret>();
            this.randevu_işlem = new HashSet<randevu_işlem>();
        }
    
        public int ID { get; set; }
        public string işlem_türü { get; set; }
        public Nullable<bool> check { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<işlem_ücret> işlem_ücret { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<randevu_işlem> randevu_işlem { get; set; }
    }
}
