//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuaför2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kuaför
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kuaför()
        {
            this.değerlendirme = new HashSet<değerlendirme>();
            this.işlem_ücret = new HashSet<işlem_ücret>();
            this.randevu = new HashSet<randevu>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public string Adres { get; set; }
        public string Telefon_numarası { get; set; }
        public string Eposta { get; set; }
        public string açılış_saati { get; set; }
        public string kapanış_saati { get; set; }
        public string şifre { get; set; }
        public Nullable<double> puan { get; set; }
        public string il { get; set; }
        public string ilçe { get; set; }
        public string Konum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<değerlendirme> değerlendirme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<işlem_ücret> işlem_ücret { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<randevu> randevu { get; set; }
    }
}
