//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuaför2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KuaförEntities25 : DbContext
    {
        public KuaförEntities25()
            : base("name=KuaförEntities25")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<değerlendirme> değerlendirme { get; set; }
        public virtual DbSet<İl> İl { get; set; }
        public virtual DbSet<İlçe> İlçe { get; set; }
        public virtual DbSet<işlem_ücret> işlem_ücret { get; set; }
        public virtual DbSet<işlemler> işlemler { get; set; }
        public virtual DbSet<Kuaför> Kuaför { get; set; }
        public virtual DbSet<müşteri> müşteri { get; set; }
        public virtual DbSet<randevu> randevu { get; set; }
        public virtual DbSet<randevu_işlem> randevu_işlem { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
