//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuaför2
{
    using System;
    using System.Collections.Generic;
    
    public partial class randevu_işlem
    {
        public int randevu { get; set; }
        public int işlem { get; set; }
        public int Id { get; set; }
    
        public virtual işlemler işlemler { get; set; }
    }
}
